import { prisma } from '../config/database.js';
import type { User } from '../types/User.js';
import bcrypt from 'bcrypt';

// Remove the id property from the User type since it is auto-generated by Prisma
type RegisterUserData = Omit<User, 'id'>;

// Create a new user
const createUser = async (user: RegisterUserData) => {
    // Hash the password
    const hashedPassword = await bcrypt.hash(user.password, 10);

    return await prisma.user.create({
        data: {
            email: user.email,
            name: user.name,
            password: hashedPassword, // Store the hashed password in the database
        },
        select: {
            id: true,
            email: true,
            name: true,
            createdAt: true,
            updatedAt: true,
            password: false, // Do not return the password in the response
        },
    });
};

export default {
    createUser,
};